### ISSUE TITLE
StackBlitz example not working

### ISSUE THREAD

**Issue by mikegoodstadt** [PSanetra/bind-observable#2]
Hi! Thanks for [sharing this](https://github.com/angular/angular/issues/5689#issuecomment-412115774).
I have created a StackBlitz of this but the bound value in the html does not update (see header).
Can you help and correct this? Or do I misunderstand the purpose of this code...?
https://stackblitz.com/edit/angular-bind-observable
Many thanks,
Mike

**Comment by PSanetra** [comment]
You created an instance of the component outside of angular. I have updated the code so that the property update and the subscription happen inside the constructor: 
https://stackblitz.com/edit/angular-bind-observable-esv89p?file=src/app/app.component.ts
```typescript
export class AppComponent  {
  name = 'Angular';
  @BindObservable()
  public myProp: string = 'initialValue';
  public myProp$: Observable<string>;

  constructor() {
    this.myProp$.subscribe(console.log);
    this.myProp = 'newValue';
  }

}
```

I also have updated the template so that it binds to the observable property:
`<hello name="{{ myProp$ | async }}"></hello>`

**Comment by mikegoodstadt** [comment]
Many thanks Philip!
I have updated my StackBlitz if you would like to use it as a demo:
https://stackblitz.com/edit/angular-bind-observable
It may be useful for others to update the Readme text.
All the best, Mike
